# ------------------------------
# 1. PersistentVolumes (static)
# ------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/nginx/pv0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/nginx/pv1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/nginx/pv2
---
# ------------------------------
# 2. PersistentVolumeClaims
# ------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-pv-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-pv-2
---
# ------------------------------
# 3. Headless Service
# ------------------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: None
  ports:
    - port: 80
      name: web
  selector:
    app: nginx
---
# ------------------------------
# 4. StatefulSet
# ------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: nginx
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: nginx-data
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates: []
  # Instead of volumeClaimTemplates, we manually define volumes below.
  volumeMounts: []
  # Volumes are defined at the Pod level using "volumeClaimTemplates" or "volumes" in spec
  # However, StatefulSet doesn't allow directly assigning PVCs per replica.
  # So we must use 'volumeClaimTemplates' normally — or use a workaround below.
